name: C++ Build

on:
  push:
    branches:
      - branchMake
  pull_request:
    branches:
      - branchMake

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GCC and Make
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make

      - name: Build with Make
        run: make

      - name: Archive the binary
        uses: actions/upload-artifact@v4
        with:
          name: hyperbolic-series-binary
          path: bin/hyperbolic_series
