name: Build and Test

on:
  push:
    branches:
      - branchHTTPserver
  pull_request:
    branches:
      - branchHTTPserver

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake dpkg-dev debhelper g++ libcpprest-dev


      # Run tests
      - name: Run tests
        run: |
          sudo g++ -o test tests/test_funcA.cpp FuncA.cpp -lcpprest -lssl -lcrypto -std=c++11
          ./test
 
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/http_server:1.0 -t ${{ secrets.DOCKER_USERNAME }}/http_server:latest .

      # Step 4: Push the Docker image to your private Docker Hub repository
      - name: Push Docker Image
        run: |
          docker push --all-tags ${{ secrets.DOCKER_USERNAME }}/http_server
