name: C++ Build

on:
  push:
    branches:
      - branchMake
  pull_request:
    branches:
      - branchMake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GCC and Make
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make

      - name: Build with Make
        run: make

      - name: Verify the binary
        run: |
          if [ -f "./bin/hyperbolic_series" ]; then
            echo "Build successful!"
          else
            echo "Build failed: Binary not found."
            exit 1
          fi
