name: Build and Test

on:
  push:
    branches:
      - branchHTTPserver
  pull_request:
    branches:
      - branchHTTPserver

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake dpkg-dev debhelper g++

      # Run autogen.sh
      - name: Run autogen.sh
        run: |
          chmod +x autogen.sh
          ./autogen.sh

      # Run configure
      - name: Run configure
        run: |
          ./configure

      # Run tests
      - name: Run tests
        run: |
          make check

      - name: Archive the log tests
        uses: actions/upload-artifact@v4
        with:
          name: test_log
          path: tests/*.log 
