name: Build and Test

on:
  push:
    branches:
      - branchHTTPserver
  pull_request:
    branches:
      - branchHTTPserver

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake dpkg-dev debhelper g++ libcpprest-dev


      # Run tests
      - name: Run tests
        run: |
          sudo g++ -o test tests/test_funcA.cpp FuncA.cpp -lcpprest -lssl -lcrypto -std=c++11
          ./test

  build-and-push:
    runs-on: ubuntu-22.04
    needs: test

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push multi-architecture Docker images
      - name: Build and Push Multi-Arch Image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${{ secrets.DOCKER_USERNAME }}/http_server:latest .
