name: Build and Test

on:
  push:
    branches:
      - branchAutoTest
  pull_request:
    branches:
      - branchAutoTest

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake dpkg-dev debhelper g++

      # Run autogen.sh
      - name: Run autogen.sh
        run: |
          chmod +x autogen.sh
          ./autogen.sh

      # Run configure
      - name: Run configure
        run: |
          ./configure

      # Run tests
      - name: Run tests
        run: |
          make check

      - name: Build Debian package
        run: |
          cd app
          dpkg-buildpackage -us -uc

      - name: Archive the Debian package
        uses: actions/upload-artifact@v4
        with:
          name: hyperbolic-series
          path: ./*.deb
